// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiawVDWsJk1ArL-JV-t3QDkSMj4SNI0G0',
    appId: '1:1071047621133:web:eadb548a81e9d3a8d47344',
    messagingSenderId: '1071047621133',
    projectId: 'sem-3-project-c0252',
    authDomain: 'sem-3-project-c0252.firebaseapp.com',
    storageBucket: 'sem-3-project-c0252.appspot.com',
    measurementId: 'G-H3CPF6T8H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQUw9mf2hwCQzwfHwJyX-1yDDX6l8nhw',
    appId: '1:1071047621133:android:657258e5007540c9d47344',
    messagingSenderId: '1071047621133',
    projectId: 'sem-3-project-c0252',
    storageBucket: 'sem-3-project-c0252.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFp6YkaSaKGO6cAdj70Ya1rUGr3MCXDm4',
    appId: '1:1071047621133:ios:70adc196a0783108d47344',
    messagingSenderId: '1071047621133',
    projectId: 'sem-3-project-c0252',
    storageBucket: 'sem-3-project-c0252.appspot.com',
    iosClientId: '1071047621133-4nladlevnf42uquut0u1hnfkqq3fp606.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFp6YkaSaKGO6cAdj70Ya1rUGr3MCXDm4',
    appId: '1:1071047621133:ios:70adc196a0783108d47344',
    messagingSenderId: '1071047621133',
    projectId: 'sem-3-project-c0252',
    storageBucket: 'sem-3-project-c0252.appspot.com',
    iosClientId: '1071047621133-4nladlevnf42uquut0u1hnfkqq3fp606.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineMobile',
  );
}
